fix: change detail-footer widget Positioned to AnimatedPosition
inhibitor1217/coffee-hmm pull request #282
Opened 2022-03-26 14:52 UTC by jyuunnii

## Background
- [애플 앱 심사 reject 사유](https://appstoreconnect.apple.com/apps/1582353861/appstore/reviewsubmissions) : 디테일 페이지에서 footer 안의 버튼이 완전하게 노출되지 않는 경우가 있다.
  - 원인 : footer가 노출되는 플로우를 offset에 맞추다보니 footer height 만큼 내려가지 않으면 반쯤 노출되는 모습을 띔. (-> 애플이 문제시한 부분)
  - 해결 : offset 이 일정 영역안에 진입했을 때 = 0(보임) or = -height (숨김) 으로 변경 (-> 완전히 보이거나 완전히 숨거나 둘 중 하나)

## Developer Test
- aOS, iOS 기기 동작 테스트 완료

**as-is**
<video src="https://user-images.githubusercontent.com/40883884/160244771-b7add0dd-6536-4f7f-89e5-0ba83bd08c79.mov
" />

**to-be**
<video src="https://user-images.githubusercontent.com/40883884/160244744-6f42db26-58d8-479b-be71-02e0039138e6.mov" />

2022-03-26 14:55 UTC, jyuunnii commented
코멘트 : 일리가 있는 reject 이었다. 앱 개발 UX 경험치 +1

2022-03-27 03:31 UTC, inhibitor1217 requested changes
스크롤이 없는 페이지는 footer가 항상 숨겨져야 하는데, 항상 나와있는 것 같아요.

2022-03-27 04:12 UTC, jyuunnii commented
> 스크롤이 없는 페이지는 footer가 항상 숨겨져야 하는데, 항상 나와있는 것 같아요.

스크롤이 없는 페이지는 푸터가 항상 나와있는게 의도한건데요 !?! 복사하기 디폴트

2022-03-27 04:14 UTC, inhibitor1217 approved these changes

2022-03-27 04:15 UTC, merged