Feature/app/detail page separation
inhibitor1217/coffee-hmm pull request #55
Opened 2021-01-21 09:54 UTC by jyuunnii

2021-01-21 10:04 UTC, inhibitor1217 requested changes
다시하세요 :)

2021-01-23 07:50 UTC, jyuunnii commented
추후 작업 계획:
- api 변경
- cafe detail에서 cafe list로 back button으로 이동했을 때 이전에 들어왔던 상태 유지하기

2021-01-23 08:53 UTC, inhibitor1217 approved these changes

2021-01-23 08:53 UTC, inhibitor1217 commented on app/src/components/api/index.tsx
> +    .then(data => {return data})
암것도 안하는 3줄

2021-01-24 01:26 UTC, merged